name: movly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  google_fonts: ^6.3.2
  flutter_svg:  ^2.2.1
  iconify_flutter: ^0.0.7
  image_picker: ^1.2.1
  file_picker: 10.3.8
  flutter_image_compress: 2.4.0


    # Firebase Core (required for all Firebase services)
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.0.2
  flutter_bloc: ^9.1.1

  # .env (APIs)
  flutter_dotenv: ^6.0.0

  # Internet access:
  http: ^1.5.0

  # Cache
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Hive
  hive_generator: ^2.0.1

  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - lib/assets/icons/
    - .env