name: movly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.2

    # Firebase Core (required for all Firebase services)
  firebase_core: ^4.1.1

  firebase_auth: ^6.1.0
  google_sign_in: ^6.2.2
  cloud_firestore: ^6.0.2
  flutter_bloc: ^9.1.1

  # .env (APIs)
  flutter_dotenv: ^6.0.0

  # Internet access:
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - .env