// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC93zggPZjHRE4haeqt1MCAp6Z3SnSssV0',
    appId: '1:431161171709:web:19b0e5e6f8ca22c5276894',
    messagingSenderId: '431161171709',
    projectId: 'movies-and-series-app---movly',
    authDomain: 'movies-and-series-app---movly.firebaseapp.com',
    storageBucket: 'movies-and-series-app---movly.firebasestorage.app',
    measurementId: 'G-EZ8LNP15E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-w-VpMIcJRkHbLShDc7kezwTPD6kS0WY',
    appId: '1:431161171709:android:1eacfc8d3daa013c276894',
    messagingSenderId: '431161171709',
    projectId: 'movies-and-series-app---movly',
    storageBucket: 'movies-and-series-app---movly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE9yvEoICL77ji-a8YlcJi6_2YVp82q3M',
    appId: '1:431161171709:ios:2b3eb8ccc9f6a968276894',
    messagingSenderId: '431161171709',
    projectId: 'movies-and-series-app---movly',
    storageBucket: 'movies-and-series-app---movly.firebasestorage.app',
    iosBundleId: 'com.example.movly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE9yvEoICL77ji-a8YlcJi6_2YVp82q3M',
    appId: '1:431161171709:ios:2b3eb8ccc9f6a968276894',
    messagingSenderId: '431161171709',
    projectId: 'movies-and-series-app---movly',
    storageBucket: 'movies-and-series-app---movly.firebasestorage.app',
    iosBundleId: 'com.example.movly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC93zggPZjHRE4haeqt1MCAp6Z3SnSssV0',
    appId: '1:431161171709:web:5c1dbbfe4d035ba9276894',
    messagingSenderId: '431161171709',
    projectId: 'movies-and-series-app---movly',
    authDomain: 'movies-and-series-app---movly.firebaseapp.com',
    storageBucket: 'movies-and-series-app---movly.firebasestorage.app',
    measurementId: 'G-J8C0CVY15V',
  );
}
